apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcpvenom
  namespace: mcpvenom
  labels:
    app.kubernetes.io/name: mcpvenom
    app.kubernetes.io/part-of: agentsmith
automountServiceAccountToken: true
